#!/usr/local/bin/node

let fs = require("fs");
Phrase = require("leighmforrest-palindrome");

let text = fs.readFileSync("phrases.txt", "utf-8");
text.split("\n").forEach(function(line){
    let phrase = new Phrase(line);
    if (phrase.palindrome()) {
        console.log("palindrome detected:", line);
    }
});
