#!/usr/local/bin/node

// Returns the paragraphs from a Wikipedia link, stripped of reference numbers.
// Especially useful for text-to-speech (both native and foreign)

let request = require('request');
let url = process.argv[2];

const jsdom = require("jsdom");
const { JSDOM } = jsdom;

if (url){
        request(url, (error, response, body)=> {
            // Simulate a Document Object Model.
            let { document } = (new JSDOM(body)).window;
            let paragraphs = document.querySelectorAll("p");
            let references = document.querySelectorAll(".reference");

            // Remov any references.
            references.forEach((reference)=>{
                reference.remove();
            });

            // Print out all the paragraphs.
            paragraphs.forEach((paragraph)=>{
                console.log(paragraph.textContent + "\n");
            });
        });
    } else {
        console.log("You must enter a url to run this script.");
        process.exit();
    }
